### ISSUE TITLE
当主动指定了 permalink 时，插件似乎无法正确处理

### ISSUE THREAD

**Issue by LeifWebber** [uuanqin/hexo-filter-titlebased-link#5]
在根目录的 `_config.yml` 中，我有如下配置：  
```yml
permalink: :hash
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
```
当我在文章的 front-matter 里不指定 permalink 时，插件正常工作。  
但是如果我手动填写了 permalink ，比如：

`Giving_Thanks_To_Qin.md`：
```yml
---
title: Giving Thanks To Qin
date: 2024/12/29
permalink: uuanqin
---
```

`Appreciation.md`：
```txt
........
Here is a link : [[Giving Thanks To Qin]].
......
```

预期中，执行 `hexo s` 后，链接应该被渲染成这样：
`localhost:4000/uuanqin`

但实际上，链接被错误的渲染成了这样：
`uuanqin`

我的版本：
`"hexo-filter-titlebased-link": "^0.2.4"`
